### ISSUE TITLE
Rename script?

### ISSUE THREAD

**Issue by sirselim** [leahkemp/ont_human_workflow#5]
I noticed that the guppy script still refers to Cthulhu, which is a server that it was written for ([this script](https://github.com/leahkemp/ont_human_workflow/blob/main/scripts/module_scripts/01-cthulhu-guppy-gpu.sh)). To keep things tidy it should probably be renamed to `01-ont-guppy-gpu.sh`. I would usually do this as a pull request but I'm picking there are a few instances where the term `cthulhu` has been used in documentation as well as input/output, so it may not be a simple find/replace - or it might be. :smile:

**Comment by leahkemp** [comment]
Done, ta
