### ISSUE TITLE
Adjustments for target capture data

### ISSUE THREAD

**Issue by sirselim** [leahkemp/ont_human_workflow#9]
I forgot to mention that if you are working with capture data, i.e. adaptive sampling experiments, then you can (and should) provide a bed file to certain scripts during the processing. This is particularly important for the wf-human-variation process, as well as modbam2bed. It should significantly speed up processing.

**Comment by leahkemp** [comment]
Ta, added into scripts :)

**Comment by leahkemp** [comment]
https://github.com/leahkemp/ont_human_workflow/commit/2fd0725de5c327f6f1f8fbdd17fc6092bccdd347
